### ISSUE TITLE
demo运行不了 启动就挂了

### ISSUE THREAD

**Issue by Xxj-star** [stewForAni/KotlinBox-WanAndroid#2]
![image](https://user-images.githubusercontent.com/41047773/199204423-5ce7de30-3e81-47ff-816c-064cd38f17b9.png)

**Comment by stewForAni** [comment]
真机系统版本，kotlin版本，AGP版本，Gradle版本   都是多少呢？

**Comment by Xxj-star** [comment]
真机->Android12 kotlin->1.6.10 build:gradle->4.2.2  wrapper-> 6.7.1

**Comment by stewForAni** [comment]
不好意思，太忙了，更新了gradle版本，你再试试，我这边很多机子都是正常的
