### ISSUE TITLE
构建报错了，这个有解决的方法嘛

### ISSUE THREAD

**Issue by JonYun** [stewForAni/KotlinBox-WanAndroid#4]
A problem occurred configuring root project 'KotlinBox'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find io.github.stewforani:methodtime:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/github/stewforani/methodtime/1.0.0/methodtime-1.0.0.pom
       - https://repo.maven.apache.org/maven2/io/github/stewforani/methodtime/1.0.0/methodtime-1.0.0.pom
       - file:/E:/Code/Android/KotlinBox-WanAndroid/app_plugin_repo/io/github/stewforani/methodtime/1.0.0/methodtime-1.0.0.pom
     Required by:
         project :

**Comment by lilicango** [comment]
同样，开了翻墙也不行

**Comment by playzhang** [comment]
把这个 插件删了可以构建。classpath 'io.github.stewforani:methodtime:1.0.0'

**Comment by stewForAni** [comment]
> A problem occurred configuring root project 'KotlinBox'.
> 
> > Could not resolve all files for configuration ':classpath'.
> > Could not find io.github.stewforani:methodtime:1.0.0.
> > Searched in the following locations:
> > - https://dl.google.com/dl/android/maven2/io/github/stewforani/methodtime/1.0.0/methodtime-1.0.0.pom
> > - https://repo.maven.apache.org/maven2/io/github/stewforani/methodtime/1.0.0/methodtime-1.0.0.pom
> > - file:/E:/Code/Android/KotlinBox-WanAndroid/app_plugin_repo/io/github/stewforani/methodtime/1.0.0/methodtime-1.0.0.pom
> > Required by:
> > project :

不好意思，这是个测试插件，有问题的话，自己注释掉吧

**Comment by stewForAni** [comment]
fixed
